[main]
mn_log_path = "/home/gr/桌面"     # 需要修改为 windows 路径
mn_upload_path = "/home/gr/桌面"  # 需要修改为 windows 路径
mn_log_name = "my_log"
mn_log_level = "info"
mn_grpc_host = "0.0.0.0"
mn_grpc_port = 29029
mn_http_host = "127.0.0.1"
mn_http_port = 5000

[jwt]
jwt_secret = "不负信赖"
jwt_iss = "圣农集团"
jwt_exp = 36000

[mysql_01]
my_host = "127.0.0.1"
my_port = 4000
my_user = "root"
my_pwd = "6@Q29sX+38yz4Rep*^"
my_db_name = "metaforge_db"

[redis_01]
rd_host = "127.0.0.1"
rd_port = 6379