[MAIN]
MN_LOG_PATH = "/home/gr/桌面"
MN_UPLOAD_PATH = "/home/gr/桌面"
MN_LOG_NAME = "my_log"
MN_LOG_LEVEL = "trace"
MN_SERVER_HOST = "127.0.0.1"
MN_SERVER_PORT = 5000

[MYSQL_01]
MY_HOST = "127.0.0.1"
MY_PORT = 4000
MY_USER = "root"
MY_PWD = "6@Q29sX+38yz4Rep*^"
MY_DB_NAME = "test"

[REDIS_01]
RD_HOST = "127.0.0.1"
RD_PORT = 6379