[package]
name = "myrspc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspc = "1.0.0-rc.5"
tokio = { version = "1.36.0", features = ["full"] }
